import { util } from "../../utils/util";
import { v2 } from "../../utils/v2";
import { Main } from "./baseDefs";

const mapDef = {
    mapId: 7,
    desc: {
        name: "Cobalt",
        icon: "img/gui/cobalt.svg",
        buttonCss: "btn-mode-cobalt",
    },
    assets: {
        audio: [
            { name: "spawn_01", channel: "ui" },
            { name: "ping_unlock_01", channel: "ui" },
            { name: "ambient_lab_01", channel: "ambient" },
            { name: "log_13", channel: "sfx" },
            { name: "log_14", channel: "sfx" },
            // from potato
            { name: "pumpkin_break_01", channel: "sfx" },
            { name: "potato_01", channel: "sfx" },
            { name: "potato_02", channel: "sfx" },
            { name: "potato_pickup_01", channel: "ui" },
            { name: "club_music_01", channel: "ambient" },
            { name: "club_music_02", channel: "ambient" },
            {
                name: "ambient_steam_01",
                channel: "ambient",
            },
            { name: "log_11", channel: "sfx" },
            { name: "log_12", channel: "sfx" },
        ],
        atlases: ["gradient", "loadout", "shared", "cobalt", "potato"],
    },
    biome: {
        colors: {
            background: 134680,
            water: 13681,
            beach: 6834230,
            riverbank: 4472122,
            grass: 5069416,
            underground: 1772803,
            playerSubmerge: 1192009,
            playerGhillie: 4937830,
        },
        particles: {},
    },
    lootTable: {
        // common: both common
        // rare: common + uncommon (?)
        tier_guns_common_scout: [
            { name: "glock_dual", count: 1, weight: 0.4},
            { name: "ot38_dual", count: 1, weight: 0.4},
        ],
        tier_guns_rare_scout: [
            { name: "ots30_dual", count: 1, weight: 0.4},
            { name: "p30l_dual", count: 1, weight: 0.4},
            { name: "deagle_dual", count: 1, weight: 0.25},
        ],
        tier_guns_common_sniper: [
            { name: "blr", count: 1, weight: 0.4},
            { name: "mosin", count: 1, weight: 0.4},
        ],
        tier_guns_rare_sniper: [
            { name: "mosin", count: 1, weight: 0.4},
            { name: "awc", count: 1, weight: 0.25},
        ],
        tier_guns_common_healer: [
            { name: "mk12", count: 1, weight: 0.4},
            { name: "m39", count: 1, weight: 0.4},
        ],
        tier_guns_rare_healer: [
            { name: "svd", count: 1, weight: 0.4},
            { name: "l86", count: 1, weight: 0.4},
            { name: "garand", count: 1, weight: 0.25},
        ],
        tier_guns_common_demo: [
            { name: "m870", count: 1, weight: 0.4},
            { name: "spas12", count: 1, weight: 0.4},
        ],
        tier_guns_rare_demo: [
            { name: "mp220", count: 1, weight: 0.4},
            { name: "saiga", count: 1, weight: 0.4},
            { name: "usas", count: 1, weight: 0.25},
        ],
        tier_guns_common_assault: [
            { name: "ak47", count: 1, weight: 0.4},
            { name: "hk416", count: 1, weight: 0.4},
            { name: "groza", count: 1, weight: 0.4},
            { name: "famas", count: 1, weight: 0.4},
        ],
        tier_guns_rare_assault: [
            { name: "scar", count: 1, weight: 0.4},
            { name: "grozas", count: 1, weight: 0.4},
            { name: "m4a1", count: 1, weight: 0.4},
            { name: "an94", count: 1, weight: 0.25},
        ],
        tier_guns_common_tank: [
            { name: "dp28", count: 1, weight: 0.4},
            { name: "qbb97", count: 1, weight: 0.25},
        ],
        tier_guns_rare_tank: [
            { name: "qbb97", count: 1, weight: 0.4},
            { name: "m249", count: 1, weight: 0.25},
            { name: "pkp", count: 1, weight: 0.25},
        ],
        // lets make this potato
        // from wiki, random guess
        tier_potato_perks: [
            { name: "", count: 1, weight: 480 },
            { name: "firepower", count: 1, weight: 15 },
            { name: "windwalk", count: 1, weight: 15 },
            { name: "endless_ammo", count: 1, weight: 15 },
            { name: "splinter", count: 1, weight: 15 },
            { name: "small_arms", count: 1, weight: 15 },
            { name: "takedown", count: 1, weight: 15 },
            { name: "field_medic", count: 1, weight: 15 },
            { name: "scavenger", count: 1, weight: 15 },
            { name: "chambered", count: 1, weight: 15 },
            { name: "martyrdom", count: 1, weight: 15 },
            { name: "self_revive", count: 1, weight: 15 },
            { name: "tree_climbing", count: 1, weight: 15 }
        ],

        tier_pguns: [
            // { name: "", count: 1, weight: 1},
            { "name": "famas", "count": 1, "weight": 1 },
            { "name": "hk416", "count": 1, "weight": 1 },
            { "name": "mk12", "count": 1, "weight": 1 },
            { "name": "pkp", "count": 1, "weight": 1 },
            { "name": "m249", "count": 1, "weight": 1 },
            { "name": "ak47", "count": 1, "weight": 1 },
            { "name": "scar", "count": 1, "weight": 1 },
            { "name": "dp28", "count": 1, "weight": 1 },
            { "name": "mosin", "count": 1, "weight": 1 },
            { "name": "m39", "count": 1, "weight": 1 },
            { "name": "mp5", "count": 1, "weight": 1 },
            { "name": "mac10", "count": 1, "weight": 1 },
            { "name": "ump9", "count": 1, "weight": 1 },
            { "name": "m870", "count": 1, "weight": 1 },
            { "name": "m1100", "count": 1, "weight": 1 },
            { "name": "mp220", "count": 1, "weight": 1 },
            { "name": "saiga", "count": 1, "weight": 1 },
            { "name": "ot38", "count": 1, "weight": 1 },
            { "name": "ot38_dual", "count": 1, "weight": 1 },
            { "name": "ots38", "count": 1, "weight": 1 },
            { "name": "ots38_dual", "count": 1, "weight": 1 },
            { "name": "m9", "count": 1, "weight": 1 },
            { "name": "m9_dual", "count": 1, "weight": 1 },
            { "name": "m93r", "count": 1, "weight": 1 },
            { "name": "m93r_dual", "count": 1, "weight": 1 },
            { "name": "glock", "count": 1, "weight": 1 },
            { "name": "glock_dual", "count": 1, "weight": 1 },
            { "name": "deagle", "count": 1, "weight": 1 },
            { "name": "deagle_dual", "count": 1, "weight": 1 },
            { "name": "vector", "count": 1, "weight": 1 },
            { "name": "sv98", "count": 1, "weight": 1 },
            { "name": "spas12", "count": 1, "weight": 1 },
            { "name": "qbb97", "count": 1, "weight": 1 },
            { "name": "flare_gun", "count": 1, "weight": 1 },
            { "name": "flare_gun_dual", "count": 1, "weight": 1 },
            { "name": "groza", "count": 1, "weight": 1 },
            { "name": "grozas", "count": 1, "weight": 1 },
            { "name": "scout_elite", "count": 1, "weight": 1 },
            { "name": "vss", "count": 1, "weight": 1 },
            { "name": "p30l", "count": 1, "weight": 1 },
            { "name": "p30l_dual", "count": 1, "weight": 1 },
            { "name": "scorpion", "count": 1, "weight": 1 },
            { "name": "usas", "count": 1, "weight": 1 },
            { "name": "m1014", "count": 1, "weight": 1 },
            { "name": "bar", "count": 1, "weight": 1 },
            { "name": "garand", "count": 1, "weight": 1 },
            { "name": "an94", "count": 1, "weight": 1 },
            { "name": "svd", "count": 1, "weight": 1 },
            { "name": "blr", "count": 1, "weight": 1 },
            { "name": "m4a1", "count": 1, "weight": 1 },
            { "name": "l86", "count": 1, "weight": 1 },
            { "name": "awc", "count": 1, "weight": 1 },
            { "name": "scarssr", "count": 1, "weight": 1 },
            { "name": "vector45", "count": 1, "weight": 1 },
            { "name": "m1911", "count": 1, "weight": 1 },
            { "name": "m1911_dual", "count": 1, "weight": 1 },
            { "name": "m1a1", "count": 1, "weight": 1 },
            { "name": "colt45", "count": 1, "weight": 1 },
            { "name": "colt45_dual", "count": 1, "weight": 1 },
            { "name": "model94", "count": 1, "weight": 1 },
            { "name": "mkg45", "count": 1, "weight": 1 }
        ],
        tier_pmelee: [
            { "name": "fists", "count": 1, "weight": 1 },
            { "name": "karambit_rugged", "count": 1, "weight": 1 },
            { "name": "karambit_prismatic", "count": 1, "weight": 1 },
            { "name": "karambit_drowned", "count": 1, "weight": 1 },
            { "name": "bayonet_rugged", "count": 1, "weight": 1 },
            { "name": "bayonet_woodland", "count": 1, "weight": 1 },
            { "name": "huntsman_rugged", "count": 1, "weight": 1 },
            { "name": "huntsman_burnished", "count": 1, "weight": 1 },
            { "name": "bowie_vintage", "count": 1, "weight": 1 },
            { "name": "bowie_frontier", "count": 1, "weight": 1 },
            { "name": "woodaxe", "count": 1, "weight": 1 },
            { "name": "woodaxe_bloody", "count": 1, "weight": 1 },
            { "name": "fireaxe", "count": 1, "weight": 1 },
            { "name": "katana", "count": 1, "weight": 1 },
            { "name": "katana_rusted", "count": 1, "weight": 1 },
            { "name": "katana_orchid", "count": 1, "weight": 1 },
            { "name": "naginata", "count": 1, "weight": 1 },
            { "name": "machete_taiga", "count": 1, "weight": 1 },
            { "name": "kukri_trad", "count": 1, "weight": 1 },
            { "name": "kukri_sniper", "count": 1, "weight": 1 },
            { "name": "stonehammer", "count": 1, "weight": 1 },
            { "name": "sledgehammer", "count": 1, "weight": 1 },
            { "name": "hook", "count": 1, "weight": 1 },
            { "name": "pan", "count": 1, "weight": 1 },
            { "name": "knuckles_rusted", "count": 1, "weight": 1 },
            { "name": "knuckles_heroic", "count": 1, "weight": 1 },
            { "name": "crowbar_scout", "count": 1, "weight": 1 },
            { "name": "crowbar_recon", "count": 1, "weight": 1 },
            { "name": "warhammer_tank", "count": 1, "weight": 1 },
            { "name": "spade_assault", "count": 1, "weight": 1 },
            { "name": "bonesaw_rusted", "count": 1, "weight": 1 },
            { "name": "bonesaw_healer", "count": 1, "weight": 1 },
        ]
    },
    /* STRIP_FROM_PROD_CLIENT:START */
    mapGen: {
        customSpawnRules: {
            locationSpawns: [
                {
                    type: "bunker_structure_09",
                    pos: v2.create(0.5, 0.5),
                    rad: 100,
                    retryOnFailure: true,
                },
            ],
        },
        densitySpawns: [
            {
                stone_01cb: 350,
                barrel_01: 76,
                silo_01: 8,
                crate_01: 50,
                crate_02: 4,
                crate_03: 8,
                bush_01cb: 78,
                cache_06: 12,
                tree_01cb: 100,
                hedgehog_01: 24,
                container_01: 5,
                container_02: 5,
                container_03: 5,
                container_04: 5,
                shack_01: 7,
                outhouse_01: 5,
                loot_tier_1: 24,
                loot_tier_beach: 4,
                // new, guesses
                class_shell_01: 100,
                class_shell_02: 100,
                // potato lol
                potato_01: 50,
                potato_02: 50,
                potato_03: 50,
            },
        ],
        fixedSpawns: [
            {
                warehouse_01: 2,
                house_red_01: { small: 3, large: 4 },
                house_red_02: { small: 3, large: 4 },
                barn_01: { small: 1, large: 3 },
                barn_02: 1,
                hut_01: 3,
                hut_02: 1, // spas hut
                hut_03: 1, // scout hut
                shack_03a: 2,
                shack_03b: { small: 2, large: 3 },
                cache_01: 1,
                cache_02: 1, // mosin tree
                cache_07: 1,
                bunker_structure_01: { odds: 0.05 },
                bunker_structure_02: 1,
                bunker_structure_03: 1,
                bunker_structure_04: 1,
                bunker_structure_05: 1,
                warehouse_complex_01: 1,
                chest_01: 1,
                chest_03: { odds: 0.2 },
                mil_crate_02: { odds: 0.25 },
                teahouse_complex_01su: {
                    small: 1,
                    large: 2,
                },
                stone_04: 1,
                club_complex_01: 1,
                bunker_structure_09: 1
            },
        ],
        randomSpawns: [
            {
                spawns: ["mansion_structure_01", "police_01"],
                choose: 2,
            },
        ],
        spawnReplacements: [
            { stone_03: "stone_03cb" }
        ],
        importantSpawns: ["bunker_structure_09"],
    },
    /* STRIP_FROM_PROD_CLIENT:END */
    gameMode: {
        maxPlayers: 80,
        perkMode: true,
        perkModeRoles: ["scout", "sniper", "healer", "demo", "assault", "tank"],
        // perkModeRoles: ["scout", "sniper", "healer", "demo", "assault", "tank", "leader"],
    },
};

export const Cobalt = util.mergeDeep({}, Main, mapDef);
